networks:
  localnet:
    ipam:
      config:
        - subnet: 10.0.0.0/16
          gateway: 10.0.0.1

services:

  nginx:
    image: nginx:latest
    volumes:
      - ./config/nginx.conf/:/etc/nginx/conf.d/default.conf
      #      - ./config/nginx.conf/:/etc/nginx/conf.d/nginx.conf
      - ./frontend/dist/frontend:/usr/share/nginx/html/
      - ./public/assets:/usr/share/nginx/html/files/
    ports:
      - "80:80"
    networks:
      localnet:
        ipv4_address: 10.0.0.2

  builder-be:
    profiles: [prod]
    image: backend-builder
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    networks:
      localnet:
        ipv4_address: 10.0.0.3

  backend:
    profiles: [prod]
    image: backend
    volumes:
      - ./public/assets:/app/public/assets
      - ./src/logs:/app/public/logs
    build:
      context: .
      dockerfile: Dockerfile
      target: app
    ports:
      - "8181:8181"
    depends_on:
      - builder-be
    #       - postgres
    environment:
      - SERVER_PORT=8181
      - SPRING_DATASOURCE_URL=jdbc:postgresql://10.0.0.6:5432/terrestrial_tutor
      - SPRING_DATASOURCE_USERNAME=tutor
      - SPRING_DATASOURCE_PASSWORD=tErRrEsTrIaLtUtOr
    networks:
      localnet:
        ipv4_address: 10.0.0.4

  frontend:
    image: node:18.20.1-alpine
    working_dir: /usr/src/app
    command: sh -c "npm install && npm run watch"
    volumes:
      - ./frontend:/usr/src/app
    networks:
      localnet:
        ipv4_address: 10.0.0.5

  #Uncomment if it's server
  postgres:
    image: postgres:16.1
    build:
      context: .
      dockerfile: Dockerfile
      target: postgres
    environment:
      POSTGRES_DB: terrestrial_tutor
      POSTGRES_PASSWORD: tErRrEsTrIaLtUtOr
      POSTGRES_USER: tutor
      command: "bin/bash cron"
    ports:
      - '5432:5432'
    volumes:
      - ./db_snapshots/:/dumps
      - ./db_snapshots/init:/docker-entrypoint-initdb.d/
    networks:
      localnet:
        ipv4_address: 10.0.0.6

  pgadmin:
    profiles: [prod]
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin2024
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 5050:80
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres
