services:

  builder-be:
    image: backend-builder
    build:
      context: .
      dockerfile: Dockerfile
      target: builder

  backend:
    image: client
    build:
      context: .
      dockerfile: Dockerfile
      target: app
    ports:
      - "8181:8181"
    depends_on:
       - builder-be
       - postgres
    environment:
      - SERVER_PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://87.249.49.62:5432/terrestrial_tutor
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=tErRrEsTrIaLtUtOr

#Uncomment if it's server
  postgres:
    image: postgres:16.1
    environment:
        POSTGRES_DB: terrestrial_tutor
        POSTGRES_PASSWORD: tErRrEsTrIaLtUtOr
        POSTGRES_USER: admin
    ports:
      - '5432:5432'
    volumes:
      - /shema.sql:/
