CREATE SEQUENCE IF NOT EXISTS enrollments_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS enrollments_sequence START WITH 1 INCREMENT BY 10;

CREATE SEQUENCE IF NOT EXISTS enrolls_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS enrolls_sequence START WITH 1 INCREMENT BY 10;

CREATE SEQUENCE IF NOT EXISTS hibernate_sequence START WITH 1 INCREMENT BY 10;

CREATE TABLE admins
(
    id         BIGINT NOT NULL,
    email      VARCHAR(255),
    name       VARCHAR(255),
    password   VARCHAR(255),
    patronymic VARCHAR(255),
    role       INTEGER,
    surname    VARCHAR(255),
    username   VARCHAR(255),
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT admins_pkey PRIMARY KEY (id)
);

CREATE TABLE checks
(
    id             BIGINT NOT NULL,
    candidate_id   BIGINT,
    date           TIMESTAMP WITHOUT TIME ZONE,
    candidate_role INTEGER,
    created_at     TIMESTAMP WITHOUT TIME ZONE,
    updated_at     TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT checks_pkey PRIMARY KEY (id)
);

CREATE TABLE enrollments
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    pupil      BIGINT,
    subject    BIGINT,
    tutor      BIGINT,
    CONSTRAINT enrollments_pkey PRIMARY KEY (id)
);

CREATE TABLE enrolls
(
    id      INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    pupil   BIGINT,
    subject BIGINT,
    tutor   BIGINT,
    CONSTRAINT enrolls_pkey PRIMARY KEY (id)
);

CREATE TABLE flyway_schema_history
(
    installed_rank INTEGER       NOT NULL,
    version        VARCHAR(50),
    description    VARCHAR(200)  NOT NULL,
    type           VARCHAR(20)   NOT NULL,
    script         VARCHAR(1000) NOT NULL,
    checksum       INTEGER,
    installed_by   VARCHAR(100)  NOT NULL,
    installed_on   TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    execution_time INTEGER       NOT NULL,
    success        BOOLEAN       NOT NULL,
    CONSTRAINT flyway_schema_history_pk PRIMARY KEY (installed_rank)
);

CREATE TABLE homework_solutions
(
    id             BIGINT NOT NULL,
    answers        TEXT,
    attempt_number INTEGER,
    homework       BIGINT,
    pupil          BIGINT,
    solution_date  BIGINT,
    status         INTEGER,
    attempt_points BIGINT,
    created_at     TIMESTAMP WITHOUT TIME ZONE,
    updated_at     TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT homework_solutions_pkey PRIMARY KEY (id)
);

CREATE TABLE homeworks
(
    id                  BIGINT NOT NULL,
    dead_line           date,
    name                VARCHAR(255),
    solute_time         BIGINT,
    target_time         BIGINT,
    subject             BIGINT,
    task_checking_types TEXT,
    created_at          TIMESTAMP WITHOUT TIME ZONE,
    updated_at          TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT homeworks_pkey PRIMARY KEY (id)
);

CREATE TABLE homeworks_pupils
(
    homework_list_id BIGINT NOT NULL,
    pupils_id        BIGINT NOT NULL,
    CONSTRAINT homeworks_pupils_pkey PRIMARY KEY (homework_list_id, pupils_id)
);

CREATE TABLE homeworks_tutors
(
    homework_list_id BIGINT NOT NULL,
    tutors_id        BIGINT NOT NULL,
    CONSTRAINT homeworks_tutors_pkey PRIMARY KEY (homework_list_id, tutors_id)
);

CREATE TABLE payments
(
    id          BIGINT NOT NULL,
    lesson_date date,
    lesson_time time WITHOUT TIME ZONE,
    status      VARCHAR(255),
    pupil       BIGINT,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT payments_pkey PRIMARY KEY (id)
);

CREATE TABLE pupil_answers
(
    id         BIGINT NOT NULL,
    answer     VARCHAR(255),
    created_at TIMESTAMP WITHOUT TIME ZONE,
    points     INTEGER,
    status     INTEGER,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    attempt    BIGINT,
    task_id    BIGINT,
    CONSTRAINT pupil_answers_pkey PRIMARY KEY (id)
);

CREATE TABLE pupils
(
    id           BIGINT NOT NULL,
    balance      DOUBLE PRECISION,
    email        VARCHAR(255),
    name         VARCHAR(255),
    password     VARCHAR(255),
    patronymic   VARCHAR(255),
    price        INTEGER,
    role         INTEGER,
    surname      VARCHAR(255),
    username     VARCHAR(255),
    verification BOOLEAN,
    support      BIGINT,
    created_at   TIMESTAMP WITHOUT TIME ZONE,
    updated_at   TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pupils_pkey PRIMARY KEY (id)
);

CREATE TABLE subjects
(
    id          BIGINT NOT NULL,
    count_level INTEGER,
    name        VARCHAR(255),
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT subjects_pkey PRIMARY KEY (id)
);

CREATE TABLE supports
(
    id           BIGINT NOT NULL,
    email        VARCHAR(255),
    name         VARCHAR(255),
    password     VARCHAR(255),
    patronymic   VARCHAR(255),
    payment_data VARCHAR(255),
    role         INTEGER,
    surname      VARCHAR(255),
    telegram_tag VARCHAR(255),
    username     VARCHAR(255),
    created_at   TIMESTAMP WITHOUT TIME ZONE,
    updated_at   TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT supports_pkey PRIMARY KEY (id)
);

CREATE TABLE task_files
(
    entity_id BIGINT NOT NULL,
    files     VARCHAR(255)
);

CREATE TABLE task_tables
(
    id         BIGINT NOT NULL,
    name       VARCHAR(255),
    tack_table VARCHAR(255),
    CONSTRAINT task_tables_pkey PRIMARY KEY (id)
);

CREATE TABLE tasks
(
    id          BIGINT NOT NULL,
    answer_type VARCHAR(255),
    checking    INTEGER,
    level1      VARCHAR(255),
    level2      VARCHAR(255),
    name        VARCHAR(255),
    tables      VARCHAR(255),
    task_text   TEXT,
    subject     BIGINT,
    support     BIGINT,
    answers     TEXT,
    analysis    TEXT,
    cost        INTEGER,
    crdate      BIGINT,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT tasks_pkey PRIMARY KEY (id)
);

CREATE TABLE tasks_checking
(
    id            BIGINT NOT NULL,
    checking_type INTEGER,
    created_at    TIMESTAMP WITHOUT TIME ZONE,
    updated_at    TIMESTAMP WITHOUT TIME ZONE,
    homework      BIGINT,
    task_id       BIGINT,
    CONSTRAINT tasks_checking_pkey PRIMARY KEY (id)
);

CREATE TABLE tutors
(
    id           BIGINT NOT NULL,
    email        VARCHAR(255),
    name         VARCHAR(255),
    password     VARCHAR(255),
    patronymic   VARCHAR(255),
    payment_data VARCHAR(255),
    role         INTEGER,
    surname      VARCHAR(255),
    username     VARCHAR(255),
    verification BOOLEAN,
    created_at   TIMESTAMP WITHOUT TIME ZONE,
    updated_at   TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT tutors_pkey PRIMARY KEY (id)
);

ALTER TABLE enrolls
    ADD CONSTRAINT uniq_record UNIQUE (tutor, pupil, subject);

CREATE INDEX flyway_schema_history_s_idx ON flyway_schema_history (success);

ALTER TABLE pupil_answers
    ADD CONSTRAINT fk29qi4wij5jy2su7b29y9r0qfu FOREIGN KEY (task_id) REFERENCES tasks (id) ON DELETE NO ACTION;

ALTER TABLE tasks
    ADD CONSTRAINT fk3fecy7xvqv5hq1a6sssq06ecy FOREIGN KEY (subject) REFERENCES subjects (id) ON DELETE NO ACTION;

ALTER TABLE enrollments
    ADD CONSTRAINT fk3moc0nk0bmrutvems92jy6g5t FOREIGN KEY (tutor) REFERENCES tutors (id) ON DELETE NO ACTION;

ALTER TABLE tasks_checking
    ADD CONSTRAINT fk60bqry75x6o2gteukl3ejo962 FOREIGN KEY (homework) REFERENCES homeworks (id) ON DELETE NO ACTION;

ALTER TABLE enrolls
    ADD CONSTRAINT fk6kcqeutkqkirnro46l05q44e0 FOREIGN KEY (subject) REFERENCES subjects (id) ON DELETE NO ACTION;

ALTER TABLE payments
    ADD CONSTRAINT fk7y9o12w5ygb7r4tee03bprjwm FOREIGN KEY (pupil) REFERENCES pupils (id) ON DELETE NO ACTION;

ALTER TABLE homework_solutions
    ADD CONSTRAINT fk80jot60ffplfhm25tj1o8gag4 FOREIGN KEY (pupil) REFERENCES pupils (id) ON DELETE NO ACTION;

ALTER TABLE enrollments
    ADD CONSTRAINT fk9e41eel5mkqijlox3thdl2lio FOREIGN KEY (pupil) REFERENCES pupils (id) ON DELETE NO ACTION;

ALTER TABLE homeworks_pupils
    ADD CONSTRAINT fka0gdm99iylmisa006c35g3d3f FOREIGN KEY (pupils_id) REFERENCES pupils (id) ON DELETE NO ACTION;

ALTER TABLE enrollments
    ADD CONSTRAINT fkagk6mbbuk02x3dl7ycchpk8xg FOREIGN KEY (subject) REFERENCES subjects (id) ON DELETE NO ACTION;

ALTER TABLE homeworks_tutors
    ADD CONSTRAINT fkbf2d77oiplxg4qyynnnfoghss FOREIGN KEY (tutors_id) REFERENCES tutors (id) ON DELETE NO ACTION;

ALTER TABLE tasks
    ADD CONSTRAINT fkfyh73ix9c2fv1lol06taqt3g8 FOREIGN KEY (support) REFERENCES supports (id) ON DELETE NO ACTION;

ALTER TABLE homeworks_pupils
    ADD CONSTRAINT fkg92hv6go2xf1m9w10mp70dieg FOREIGN KEY (homework_list_id) REFERENCES homeworks (id) ON DELETE NO ACTION;

ALTER TABLE homeworks_tutors
    ADD CONSTRAINT fkh1fxmhx537mi2h2usrhg02fe2 FOREIGN KEY (homework_list_id) REFERENCES homeworks (id) ON DELETE NO ACTION;

ALTER TABLE pupil_answers
    ADD CONSTRAINT fkhhr8ai39kqavwvem9em11cm6i FOREIGN KEY (attempt) REFERENCES homework_solutions (id) ON DELETE NO ACTION;

ALTER TABLE pupils
    ADD CONSTRAINT fki40kcsrgjp9ha060c1x21h72x FOREIGN KEY (support) REFERENCES supports (id) ON DELETE NO ACTION;

ALTER TABLE tasks_checking
    ADD CONSTRAINT fkiv8lftp0uv6fy8ayijsjslibh FOREIGN KEY (task_id) REFERENCES tasks (id) ON DELETE NO ACTION;

ALTER TABLE enrolls
    ADD CONSTRAINT fkmrykj3dbv0kubp2s49jb44gok FOREIGN KEY (pupil) REFERENCES pupils (id) ON DELETE NO ACTION;

ALTER TABLE task_files
    ADD CONSTRAINT fkms6xiwrvlcfy7l1k57lwpidn5 FOREIGN KEY (entity_id) REFERENCES tasks (id) ON DELETE NO ACTION;

ALTER TABLE homework_solutions
    ADD CONSTRAINT fkn6ahn0iq9atidmf2r7b0u8gmx FOREIGN KEY (homework) REFERENCES homeworks (id) ON DELETE NO ACTION;

ALTER TABLE enrolls
    ADD CONSTRAINT fknc7p17xq11cj9s5lnfo751x4q FOREIGN KEY (tutor) REFERENCES tutors (id) ON DELETE NO ACTION;

ALTER TABLE homeworks
    ADD CONSTRAINT fkqgmfv0bm7k8460rjn0rg9twc1 FOREIGN KEY (subject) REFERENCES subjects (id) ON DELETE NO ACTION;