name: Build
on:
  push:
    branches:
      - devel
  pull_request:
    types:
      - opened
    branches:
      - master

jobs:
  build:
    name: Build check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker compose build && docker compose up -d
        name: Build