name: Deploy

on:
  push:
    branches: [ "changes" ]
  pull_request:
    branches: [ "changes" ]
    
defaults:
  run:
    shell: bash
    working-directory: /home/tutor/terrestrial_tutor

jobs:

  deploy:

    runs-on: self-hosted

    steps:
        - name: Deploy changes
        - run: git pull && docker compose restart nginx
