name: Deploy

on:
  push:
    branches: [ "changes" ]
  pull_request:
    branches: [ "changes" ]

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v4 
        - name: Deploy changes
          run: echo ${{ secrets.DEPLOY_SSH }}
