name: Deploy

on:
  push:
    branches: [ "changes" ]
  pull_request:
    branches: [ "changes" ]

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:  
        - uses: actions/checkout@v4 
        - name: Deploy changes
          uses: easingthemes/ssh-deploy@main
          with:
            SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_SSH }}
            ARGS: ""
            SOURCE: "./"
            REMOTE_HOST: 87.249.49.62
            REMOTE_USER: tutor
            TARGET: "/home/tutor"
            SCRIPT_AFTER: |
              ls
