name: Deploy

on:
  pull_request:
    types:
    - closed
    branches:
    - master

jobs:

  build:

    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:  
      - uses: actions/checkout@v4
      - run: docker compose build && docker compose up -d
        name: Build

  deploy:

    runs-on: ubuntu-latest
    needs: build
    if: github.event.pull_request.merged == true
    steps:
      - name: Deploy to live
        uses: D3rHase/ssh-command-action@v0.2.2
        with:
          host: 87.249.49.62
          user: tutor
          private_key: ${{ secrets.DEPLOY_SSH }}
          command: |
            cd /home/tutor/terrestrial_tutor;
            git checkout master;
            git pull;
            docker compose down backend frontend nginx;
            docker compose up -d --build backend;
            docker compose up -d frontend nginx;
