name: Deploy

on:
  push:
    branches: [ "changes" ]
  pull_request:
    branches: [ "changes" ]

jobs:

  deploy:

    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
      - name: Deploy changes
        run: gut pull && docker compose restart nginx
