name: Deploy

on:
  push:
    branches: [ "changes" ]
  pull_request:
    branches: [ "changes" ]

jobs:

  deploy:

    runs-on: self-hosted

    steps:
        - uses: actions/checkout@v4 
          with:
            set-safe-directory: false
        - name: Deploy changes
          working-directory: ./
          run: docker compose restart nginx
