name: Deploy

on:
  push:
    branches: [ "changes" ]
  pull_request:
    branches: [ "changes" ]

jobs:

  deploy:

    runs-on: self-hosted

    steps:
        - name: Deploy changes
          working-directory: /home/tutor
          run: git pull && docker compose restart nginx
