name: Deploy

on:
  push:
    branches: [ "changes" ]
  pull_request:
    branches: [ "changes" ]

jobs:

  deploy:

    runs-on: self-hosted

    steps:
        - name: Checkout
          uses: actions/checkout@v4
          with:
            path: /home/tutor/terrestrial_tutor
    
        - name: Deploy changes
          run: git pull && docker compose restart nginx
